#!/usr/bin/env python3
"""
Parse every YAML rule under Detections/ and Hunting Queries/, then emit:
  - coverage.md                  (Markdown ATT&CK matrix)
  - attack-navigator/layer.json  (drop into mitre-attack.github.io/attack-navigator)

Stdlib only. Run from repo root: python scripts/generate_coverage.py
"""
from __future__ import annotations

import json
import re
import sys
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
RULE_DIRS = [REPO / "Detections", REPO / "Hunting Queries"]
COVERAGE_MD = REPO / "coverage.md"
LAYER_JSON = REPO / "attack-navigator" / "layer.json"


def parse_minimal_yaml(text: str) -> dict:
    """Pull just the top-level scalar / list fields we need from a rule YAML.
    Avoids a pyyaml dependency so CI stays stdlib-only."""
    out: dict = {}
    lines = text.splitlines()
    i = 0
    current_list_key: str | None = None
    while i < len(lines):
        raw = lines[i]
        line = raw.rstrip()
        if not line or line.lstrip().startswith("#"):
            i += 1
            continue
        if line.startswith("  - ") and current_list_key:
            out.setdefault(current_list_key, []).append(line[4:].strip().strip('"'))
            i += 1
            continue
        m = re.match(r"^([A-Za-z][A-Za-z0-9_]*):\s*(.*)$", line)
        if m:
            key, val = m.group(1), m.group(2).strip()
            if not val:
                current_list_key = key
                out.setdefault(key, [])
            else:
                current_list_key = None
                out[key] = val.strip('"').strip("'")
        i += 1
    return out


def collect() -> list[dict]:
    rules = []
    for d in RULE_DIRS:
        if not d.is_dir():
            continue
        for path in sorted(d.glob("*.yaml")):
            try:
                meta = parse_minimal_yaml(path.read_text(encoding="utf-8"))
            except Exception as exc:
                print(f"WARN: failed to parse {path}: {exc}", file=sys.stderr)
                continue
            techniques = meta.get("relevantTechniques") or []
            tactics = meta.get("tactics") or []
            rules.append({
                "file": path.relative_to(REPO).as_posix(),
                "name": meta.get("name", path.stem),
                "kind": "Detection" if d.name == "Detections" else "Hunt",
                "severity": meta.get("severity", "—"),
                "tactics": tactics,
                "techniques": techniques,
            })
    return rules


def write_coverage_md(rules: list[dict]) -> None:
    by_tech: dict[str, list[dict]] = defaultdict(list)
    for r in rules:
        for t in r["techniques"]:
            by_tech[t].append(r)
    all_tactics = sorted({t for r in rules for t in r["tactics"]})
    lines = [
        "# ATT&CK Coverage",
        "",
        "Auto-generated by `scripts/generate_coverage.py`. Do not edit by hand.",
        "",
        f"- **Rules:** {sum(1 for r in rules if r['kind']=='Detection')} detections + "
        f"{sum(1 for r in rules if r['kind']=='Hunt')} hunts",
        f"- **Unique techniques:** {len(by_tech)}",
        f"- **Tactics covered:** {len(all_tactics)} ({', '.join(all_tactics)})",
        "",
        "## Techniques → Rules",
        "",
        "| Technique | Rule | Type | Severity |",
        "|---|---|---|---|",
    ]
    for tech in sorted(by_tech):
        for r in by_tech[tech]:
            lines.append(f"| `{tech}` | [{r['name']}]({r['file']}) | {r['kind']} | {r['severity']} |")
    COVERAGE_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {COVERAGE_MD.relative_to(REPO)}")


def write_navigator_layer(rules: list[dict]) -> None:
    by_tech: dict[str, list[dict]] = defaultdict(list)
    for r in rules:
        for t in r["techniques"]:
            by_tech[t].append(r)
    techniques = []
    for tech, hits in by_tech.items():
        comment = "; ".join(f"{r['name']} ({r['kind']})" for r in hits)
        techniques.append({
            "techniqueID": tech,
            "score": min(100, 25 * len(hits)),
            "color": "",
            "comment": comment,
            "enabled": True,
        })
    layer = {
        "name": "sentinel-hunt-pack coverage",
        "versions": {"attack": "14", "navigator": "4.9.1", "layer": "4.5"},
        "domain": "enterprise-attack",
        "description": "ATT&CK coverage produced by github.com/sandeepmothukuri/sentinel-hunt-pack",
        "techniques": techniques,
        "gradient": {
            "colors": ["#dde4ee", "#2776d6", "#0d3a76"],
            "minValue": 0,
            "maxValue": 100,
        },
        "legendItems": [
            {"label": "1 rule",  "color": "#dde4ee"},
            {"label": "2 rules", "color": "#2776d6"},
            {"label": "3+ rules","color": "#0d3a76"},
        ],
    }
    LAYER_JSON.parent.mkdir(parents=True, exist_ok=True)
    LAYER_JSON.write_text(json.dumps(layer, indent=2), encoding="utf-8")
    print(f"Wrote {LAYER_JSON.relative_to(REPO)}")


def main() -> int:
    rules = collect()
    if not rules:
        print("No rules found.", file=sys.stderr)
        return 1
    write_coverage_md(rules)
    write_navigator_layer(rules)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
